import React, { useState, useEffect } from "react";
import { Card, Row, Col, Badge, Button, Table, Container, Spinner, Alert } from "react-bootstrap";
import { FileText, Download, MapPin, Calendar, AlertTriangle, CheckCircle } from "lucide-react";
import { jsPDF } from "jspdf";
import "jspdf-autotable";
import { useSearchParams } from "react-router-dom";
import { getSiteById, getDetectedSites } from "../services/api";

export default function Reports() {
  const [searchParams] = useSearchParams();
  const siteId = searchParams.get("id");
  const [site, setSite] = useState(null);
  const [allSites, setAllSites] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generatingPDF, setGeneratingPDF] = useState(false);

  useEffect(() => {
    loadReportData();
  }, [siteId]);

  const loadReportData = () => {
    setLoading(true);
    
    if (siteId) {
      const foundSite = getSiteById(siteId);
      setSite(foundSite);
    } else {
      // Show all sites if no ID provided
      const sites = getDetectedSites();
      setAllSites(sites);
      if (sites.length > 0) {
        setSite(sites[0]); // Show first site by default
      }
    }
    
    setLoading(false);
  };

  const handleDownloadPDF = () => {
    if (!site) return;
    
    setGeneratingPDF(true);
    
    const doc = new jsPDF();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("HYDRAA - Illegal Construction Detection Report", 20, 20);
    
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Report Generated: ${new Date().toLocaleString()}`, 20, 35);
    
    // Site Information
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.text("Site Information", 20, 50);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    let yPos = 60;
    
    const siteData = [
      ["Site ID", site.id],
      ["Construction Type", site.type],
      ["District", site.district],
      ["Coordinates", `${site.coordinates.lat.toFixed(6)}, ${site.coordinates.lng.toFixed(6)}`],
      ["Area", `${Math.round(site.area)} m²`],
      ["Risk Level", site.riskLevel],
      ["Status", site.status],
      ["Detected Date", new Date(site.detectedDate).toLocaleDateString()],
      ["Confidence", `${(site.confidence * 100).toFixed(1)}%`]
    ];
    
    doc.autoTable({
      startY: yPos,
      head: [["Field", "Value"]],
      body: siteData,
      theme: "grid",
      styles: { fontSize: 10 },
      margin: { left: 20, right: 20 }
    });
    
    yPos = doc.lastAutoTable.finalY + 15;
    
    // Violations
    if (site.violations && site.violations.length > 0) {
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.text("Detected Violations", 20, yPos);
      
      const violationData = site.violations.map(v => [
        v.type,
        v.feature,
        v.severity,
        v.distance || "N/A"
      ]);
      
      doc.autoTable({
        startY: yPos + 10,
        head: [["Violation Type", "Feature", "Severity", "Distance"]],
        body: violationData,
        theme: "grid",
        styles: { fontSize: 9 },
        margin: { left: 20, right: 20 }
      });
    }
    
    // Add notes
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Remarks:", 20, doc.lastAutoTable.finalY + 15);
    doc.setFont("helvetica", "normal");
    doc.text(site.remarks || "No additional remarks", 20, doc.lastAutoTable.finalY + 25);
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text("Generated by HYDRAA AI-UrbanVision System", 20, doc.internal.pageSize.height - 10);
    
    doc.save(`site_report_${site.id}.pdf`);
    setGeneratingPDF(false);
  };

  if (loading) {
    return (
      <Container className="text-center py-5">
        <Spinner animation="border" />
        <p className="mt-3">Loading report...</p>
      </Container>
    );
  }

  if (!site) {
    return (
      <Container className="py-5">
        <Alert variant="info">
          <AlertTriangle size={20} className="me-2" />
          No site report found. Please select a site from the dashboard.
        </Alert>
        <Button variant="primary" className="mt-3" onClick={() => window.location.href = "/dashboard"}>
          Go to Dashboard
        </Button>
      </Container>
    );
  }

  const getRiskBadgeVariant = (risk) => {
    return risk === "HIGH" ? "danger" : risk === "MEDIUM" ? "warning" : "success";
  };

  return (
    <Container fluid className="py-4">
      <Row className="mb-4">
        <Col>
          <div className="d-flex justify-content-between align-items-center">
            <div>
              <h2 className="fw-bold">
                <FileText className="me-2" size={32} />
                Site Report
              </h2>
              <p className="text-muted mb-0">Detailed analysis and evidence</p>
            </div>
            <Button
              variant="primary"
              onClick={handleDownloadPDF}
              disabled={generatingPDF}
            >
              {generatingPDF ? (
                <>
                  <Spinner animation="border" size="sm" className="me-2" />
                  Generating...
                </>
              ) : (
                <>
                  <Download size={18} className="me-2" />
                  Download PDF
                </>
              )}
            </Button>
          </div>
        </Col>
      </Row>

      <Row className="g-4">
        {/* Main Report Card */}
        <Col lg={8}>
          <Card className="shadow-sm mb-4">
            <Card.Header className="bg-primary text-white">
              <h4 className="mb-0">Site Information</h4>
            </Card.Header>
            <Card.Body>
              <Row>
                <Col md={6}>
                  <Table borderless>
                    <tbody>
                      <tr>
                        <td><strong>Site ID:</strong></td>
                        <td>{site.id}</td>
                      </tr>
                      <tr>
                        <td><strong>Construction Type:</strong></td>
                        <td>{site.type}</td>
                      </tr>
                      <tr>
                        <td><strong>District:</strong></td>
                        <td>{site.district}</td>
                      </tr>
                      <tr>
                        <td><strong>Coordinates:</strong></td>
                        <td>
                          <MapPin size={14} className="me-1" />
                          {site.coordinates.lat.toFixed(6)}, {site.coordinates.lng.toFixed(6)}
                        </td>
                      </tr>
                      <tr>
                        <td><strong>Area:</strong></td>
                        <td>{Math.round(site.area)} m²</td>
                      </tr>
                    </tbody>
                  </Table>
                </Col>
                <Col md={6}>
                  <Table borderless>
                    <tbody>
                      <tr>
                        <td><strong>Risk Level:</strong></td>
                        <td>
                          <Badge bg={getRiskBadgeVariant(site.riskLevel)}>
                            {site.riskLevel}
                          </Badge>
                          <small className="text-muted ms-2">(Score: {site.riskScore})</small>
                        </td>
                      </tr>
                      <tr>
                        <td><strong>Status:</strong></td>
                        <td>
                          {site.status === "RESOLVED" ? (
                            <CheckCircle size={16} className="text-success me-1" />
                          ) : (
                            <AlertTriangle size={16} className="text-warning me-1" />
                          )}
                          {site.status.replace("_", " ")}
                        </td>
                      </tr>
                      <tr>
                        <td><strong>Detected:</strong></td>
                        <td>
                          <Calendar size={14} className="me-1" />
                          {new Date(site.detectedDate).toLocaleString()}
                        </td>
                      </tr>
                      <tr>
                        <td><strong>Confidence:</strong></td>
                        <td>{(site.confidence * 100).toFixed(1)}%</td>
                      </tr>
                      {site.reportedDate && (
                        <tr>
                          <td><strong>Reported:</strong></td>
                          <td>{new Date(site.reportedDate).toLocaleDateString()}</td>
                        </tr>
                      )}
                    </tbody>
                  </Table>
                </Col>
              </Row>
            </Card.Body>
          </Card>

          {/* Violations */}
          {site.violations && site.violations.length > 0 && (
            <Card className="shadow-sm mb-4">
              <Card.Header className="bg-danger text-white">
                <h4 className="mb-0">⚠️ Detected Violations</h4>
              </Card.Header>
              <Card.Body>
                <Table responsive>
                  <thead>
                    <tr>
                      <th>Violation Type</th>
                      <th>Feature</th>
                      <th>Severity</th>
                      <th>Distance/Details</th>
                    </tr>
                  </thead>
                  <tbody>
                    {site.violations.map((violation, idx) => (
                      <tr key={idx}>
                        <td><strong>{violation.type}</strong></td>
                        <td>{violation.feature}</td>
                        <td>
                          <Badge bg={violation.severity === "HIGH" ? "danger" : "warning"}>
                            {violation.severity}
                          </Badge>
                        </td>
                        <td>{violation.distance || "N/A"}</td>
                      </tr>
                    ))}
                  </tbody>
                </Table>
              </Card.Body>
            </Card>
          )}

          {/* Before/After Comparison */}
          <Card className="shadow-sm">
            <Card.Header className="bg-info text-white">
              <h4 className="mb-0">🛰 Before/After Satellite Imagery</h4>
            </Card.Header>
            <Card.Body>
              <Row>
                <Col md={6}>
                  <div className="text-center mb-2">
                    <strong>Before Image</strong>
                    <small className="d-block text-muted">
                      Historical Baseline: <strong>2006</strong> (~18+ years ago)
                    </small>
                  </div>
                  {site.evidence?.beforeImage ? (
                    <img
                      src={site.evidence.beforeImage}
                      alt="Before"
                      className="img-fluid rounded border"
                      style={{ maxHeight: "300px", width: "100%", objectFit: "cover" }}
                      onError={(e) => {
                        e.target.src = "https://via.placeholder.com/400x300?text=Before+Image";
                      }}
                    />
                  ) : (
                    <div className="border rounded d-flex align-items-center justify-content-center bg-light" style={{ height: "300px" }}>
                      <p className="text-muted">Before image not available</p>
                    </div>
                  )}
                </Col>
                <Col md={6}>
                  <div className="text-center mb-2">
                    <strong>After Image</strong>
                    <small className="d-block text-muted">Current</small>
                  </div>
                  {site.evidence?.afterImage ? (
                    <img
                      src={site.evidence.afterImage}
                      alt="After"
                      className="img-fluid rounded border"
                      style={{ maxHeight: "300px", width: "100%", objectFit: "cover" }}
                      onError={(e) => {
                        e.target.src = "https://via.placeholder.com/400x300?text=After+Image";
                      }}
                    />
                  ) : (
                    <div className="border rounded d-flex align-items-center justify-content-center bg-light" style={{ height: "300px" }}>
                      <p className="text-muted">After image not available</p>
                    </div>
                  )}
                </Col>
              </Row>
              <Alert variant="info" className="mt-3 mb-0">
                <small>
                  <strong>Analysis Note:</strong> These satellite images compare the area from the historical baseline (2006) with current imagery.
                  This 18+ year comparison period provides maximum accuracy in detecting illegal constructions and encroachments.
                  The system identified new structures through AI-powered change detection analysis comparing imagery from 2006 to present.
                </small>
              </Alert>
            </Card.Body>
          </Card>
        </Col>

        {/* Sidebar */}
        <Col lg={4}>
          <Card className="shadow-sm mb-4">
            <Card.Header>
              <h5 className="mb-0">Quick Actions</h5>
            </Card.Header>
            <Card.Body>
              <div className="d-grid gap-2">
                <Button
                  variant="outline-primary"
                  onClick={() => window.location.href = `/site-check?lat=${site.coordinates.lat}&lng=${site.coordinates.lng}`}
                >
                  View on Map
                </Button>
                <Button
                  variant="outline-secondary"
                  onClick={() => window.location.href = "/dashboard"}
                >
                  Back to Dashboard
                </Button>
              </div>
            </Card.Body>
          </Card>

          {/* Remarks */}
          {site.remarks && (
            <Card className="shadow-sm mb-4">
              <Card.Header>
                <h5 className="mb-0">Remarks</h5>
              </Card.Header>
              <Card.Body>
                <p className="mb-0">{site.remarks}</p>
              </Card.Body>
            </Card>
          )}

          {/* Evidence Summary */}
          <Card className="shadow-sm">
            <Card.Header>
              <h5 className="mb-0">Evidence Summary</h5>
            </Card.Header>
            <Card.Body>
              <ul className="list-unstyled mb-0">
                <li className="mb-2">
                  <strong>GPS Coordinates:</strong>
                  <br />
                  <small className="text-muted">
                    {site.coordinates.lat.toFixed(6)}, {site.coordinates.lng.toFixed(6)}
                  </small>
                </li>
                <li className="mb-2">
                  <strong>Detection Confidence:</strong>
                  <br />
                  <small className="text-muted">{(site.confidence * 100).toFixed(1)}%</small>
                </li>
                <li>
                  <strong>Violations Count:</strong>
                  <br />
                  <small className="text-muted">
                    {site.violations ? site.violations.length : 0} violation(s)
                  </small>
                </li>
              </ul>
            </Card.Body>
          </Card>
        </Col>
      </Row>
    </Container>
  );
}